#!/bin/bash

#set -o nounset
set -e 

echo "--- Start $0 $*"

YEAR=$(date +"%y")
MONTH=$(date +"%m")
DAY=$(date +"%d")
WEEK=$(date +"%w")

MODE_CLEAR="help"
if [[ $# -gt 0 ]]; then
  MODE_CLEAR="$1"
  if [[ $MODE_CLEAR = 'force' ]] ; then
    if [[ ! -z $2 && $2 =~ [0-9]{2} ]]; then
      YEAR=$2
      if [[ ! -z $3 && $3 =~ [0-9]{2} ]]; then
        MONTH=$3
        if [[ ! -z $4 && $4 =~ [0-9]{2} ]]; then
          DAY=$4
        else 
          DAY=''
        fi
      fi
    fi
  fi
fi

NOW="${YEAR}${MONTH}"


DIR_BIN='./bin'
PERIOD=$("$DIR_BIN"/get_period_now $YEAR $MONTH $DAY $WEEK )

echo "$MODE_CLEAR YEAR=$YEAR MONTH=$MONTH DAY=$DAY WEEK=$WEEK PERIOD=$PERIOD NOW=$NOW"

case $MODE_CLEAR in 
        "full")
                echo $DIR_BIN/clear_remote $PERIOD
                     $DIR_BIN/clear_remote $PERIOD
                ;;
     "current") 
                echo $DIR_BIN/clear_remote $PERIOD $NOW $DAY
                     $DIR_BIN/clear_remote $PERIOD $NOW $DAY 
                ;;
       "force") 
                echo $DIR_BIN/clear_remote $PERIOD $NOW $DAY
                     $DIR_BIN/clear_remote $PERIOD $NOW $DAY
                ;;
             *) 
                echo "Usage: $0 { full | current | force yy | force yy mm | force yy mm dd}"  
                exit 1
                ;;
esac

exit 0



