#!/bin/bash

set -o nounset
set -e 

echo "--- Start $0"

### Input parameters ###
YEAR=$1
MONTH=$2
DAY=$3
WEEK=$4
DIR_ROOT=$5

### Directories ###
cd $DIR_ROOT
echo "DIR_ROOT: '${DIR_ROOT}' Current dir: '$(pwd)'"

DIR_BIN="${DIR_ROOT}"/bin
DIR_CFG="${DIR_ROOT}"/cfg
DIR_ARC="${DIR_ROOT}"/arc
DIR_LOG="${DIR_ROOT}"/log

### Prepare date and period information
PERIOD=$("$DIR_BIN"/get_period_now $YEAR $MONTH $DAY $WEEK)
NOW="${YEAR}${MONTH}"
CNT_KEEP=$("$DIR_BIN"/cnt_keep_by_period $PERIOD)
echo "YEAR=${YEAR} MONTH=${MONTH} DAY=${DAY} WEEK=${WEEK} PERIOD=${PERIOD} NOW=${NOW} KEEP=$CNT_KEEP"

"$DIR_BIN"/prepare_remote $PERIOD $CNT_KEEP

#do all backup script
SCRIPTS=' backup_db backup_data '
#SCRIPTS=' backup_db  '
#SCRIPTS=' backup_data '
for SCRIPT in $SCRIPTS;
do 
  echo "Executing: $SCRIPT"
  echo "$DIR_BIN"/$SCRIPT $PERIOD $YEAR $MONTH $DAY $WEEK "$DIR_ROOT"
       "$DIR_BIN"/$SCRIPT $PERIOD $YEAR $MONTH $DAY $WEEK "$DIR_ROOT"
done

exit 0
