#!/bin/bash

echo
echo "--- Start $0 $*"

set -o nounset
set -e 

MAIL_TO='hello@giantleaplab.com'
ERROR_FILE='backup_error.log'
MSG_ERROR='Error! Check backup'

echo
echo '---'
echo "$0 $*"
echo 'Start at '$(date +"%D %T")
echo '---'
echo

### Setup your default directories.
DIR_ROOT=$(dirname "$0")
DIR_ROOT=$("$DIR_ROOT"/bin/get_root_dir "$0") || exit_if_error $? "Check getting root dirs for $0"
DIR_BIN="$DIR_ROOT"/bin
DIR_CFG="$DIR_ROOT"/cfg
DIR_ARC="$DIR_ROOT"/arc
DIR_LOG="$DIR_ROOT"/log

if [ -d "$DIR_BIN" -a -d "$DIR_CFG"  -a -d "$DIR_ARC"  -a -d "$DIR_LOG" ]; 
then
  
  ### Input parameters ###
  YEAR=${1:-$(date +"%y")}
  MONTH=${2:-$(date +"%m")}
  DAY=${3:-$(date +"%d")}
  WEEK=${4:-$(date +"%w")}

  rm -f "$DIR_LOG"/"$ERROR_FILE"
  echo "$DIR_ROOT/full_backup $YEAR $MONTH $DAY $WEEK"
  "$DIR_ROOT"/full_backup $YEAR $MONTH $DAY $WEEK

  if [[ $? != "0" ]] ; then
    echo "Error when 'full_backup $YEAR $MONTH $DAY $WEEK'. Check log" | mail -s "$ERROR_MESS" "$MAIL_TO"
  fi

  if [[ -f "$DIR_LOG/$ERROR_FILE" ]] ; then
    cat "$DIR_LOG"/"$ERROR_FILE" | mail -s "$ERROR_MESS" "$MAIL_TO"
  fi

else
  echo 'It war error when backup. Check start directory.' | mail -s "$ERROR_MESS" "$MAIL_TO"
fi

echo
echo '---'
echo "$0"
echo 'Finish at '$(date +"%D %T")
echo '---'
echo

exit 0