#!/bin/bash

set -o nounset
set -e 

echo
echo '------------------------------------------------'
echo "$0"
echo 'Start:' $(date +"%D %T")
echo '------------------------------------------------'
echo

### Setup your defauly root of directory
DEF_ROOT='/root/server-back-scripts'

### Input parameters ###
YEAR=${1:-$(date +"%y")}
MONTH=${2:-$(date +"%m")}
DAY=${3:-$(date +"%d")}
WEEK=${4:-$(date +"%w")}
DIR_ROOT=${5:-$DEF_ROOT}

$DIR_ROOT/full_backup $YEAR $MONTH $DAY $WEEK "$DIR_ROOT"
echo
echo '------------------------------------------------'
echo "$0"
echo 'Finish:' $(date +"%D %T")
echo '------------------------------------------------'
echo
